CREATE TABLE FCT_SOURCE (
	id                            integer primary key generated by default as IDENTITY
	, name                        text
	, description                 text
	, geometry                    geometry(MultiPolygon,4326)
    , geonetwork_uuid             text
	, publication_date            date
	, notes                       text
);


COMMENT ON TABLE FCT_SOURCE IS 'The names of the various Food Composition Tables from which we derive the information about food composition';
