CREATE TABLE household_consumption (
    id                         integer primary key GENERATED BY DEFAULT AS IDENTITY
    , food_genus_id            text references food_genus (id)
    , food_genus_confidence    text references food_genus_confidence (id)
    , household_id             integer references household (id)
    , source_of_food           text CHECK (source_of_food IN ('own production', 'bought', 'gifted'))
    , date_consumed            date
    , amount_consumed_in_g     numeric(10,3)

);

COMMENT ON TABLE household_consumption IS 'What food items what been consumed by a household as a whole, and in what quantity.';
COMMENT on column household_consumption.food_genus_id         IS 'The food_genus id of the fooditem that was consumed';
COMMENT on column household_consumption.food_genus_confidence IS 'How confident we are in matching this food to the corresponding food_genus entry';
COMMENT on column household_consumption.household_id          IS 'The id of the household that consumed the food item';
COMMENT on column household_consumption.source_of_food        IS 'From where the household obtained the food; if they grew it themselves, bought it at market, or had it gifted to them';
COMMENT on column household_consumption.date_consumed         IS 'The date when the fooditem was consumed';
COMMENT on column household_consumption.amount_consumed_in_g  IS 'How much of the fooditem was consumed on average per day, in grams';
