CREATE TABLE intake_threshold (
    id                     integer primary key generated by default as IDENTITY
    , nutrient_name        text
    , unit_of_measurement  text
    , age_lower            integer
    , age_upper            integer
    , EAR                  numeric(20,10)
    , RDA                  numeric(20,10)
    , sex                  text CHECK (sex in ('Male','Female'))
    , breastfed_YN         boolean
    , lactating_YN         boolean
    , pregnant_YN          boolean
    , validity_area        geometry(Polygon,4326)
);
