CREATE TABLE foodex (
    id                     integer primary key GENERATED BY DEFAULT AS IDENTITY
    , food_name              text

);

COMMENT ON TABLE foodex IS 'List of fooditems derived from the FOODEX2 database. used to standardise and match food names from the consumption tables to the food composition table (fooditem)';
COMMENT on column foodex.food_name IS 'The name of the fooditem as given by the FOODEX" database';
