CREATE TABLE country_consumption (
    id                      integer primary key GENERATED BY DEFAULT AS IDENTITY
    , food_genus_id         text references food_genus (id)
    , food_genus_confidence text references food_genus_confidence (id)
    , country_id            text references country (id)
    , original_id           text
    , original_name         text
    , date_consumed         date
    , amount_consumed_in_g  numeric(10,3)

);

COMMENT ON TABLE COUNTRY_CONSUMPTION IS 'What food items what been consumed per capita per year in a country, and in what quantity.';
COMMENT on column COUNTRY_CONSUMPTION.food_genus_id         IS 'The food genus id of the fooditem that was consumed';
COMMENT on column COUNTRY_CONSUMPTION.original_id           IS 'The original name or id of the fooditem that was consumed';
COMMENT on column COUNTRY_CONSUMPTION.food_genus_confidence IS 'How confident we are in matching this food to the corresponding food_genus entry';
COMMENT on column COUNTRY_CONSUMPTION.country_id            IS 'The id of the country that consumed the food item';
COMMENT on column COUNTRY_CONSUMPTION.date_consumed         IS 'The year when the commodity was consumed';
COMMENT on column COUNTRY_CONSUMPTION.amount_consumed_in_g  IS 'How much of the commodity was consumed, in grams per capita';
