CREATE TABLE population_source (
	id                          integer primary key,
	"name"                      text,
	description                 text,
    geonetwork_uuid             text
);
COMMENT ON TABLE population_source IS 'The names of the data sources for population data';

create TABLE population (
	id                          integer primary key GENERATED BY DEFAULT AS IDENTITY,
	aggregation_area_id			integer REFERENCES aggregation_area (id),
	"year"						integer,
	population_source_id		integer REFERENCES population_source (id),
	min_age_in_years			integer,
	max_age_in_years			integer,
	sex							char(1),
	population					float8,
	CONSTRAINT population_sex_check CHECK ((sex = ANY (ARRAY['m'::text, 'f'::text])))
);
COMMENT ON TABLE population IS 'population of people of each sex within an age range inclusive of the min and max age living in an aggregation area ';

create TABLE population_summary (
	id                          integer primary key GENERATED BY DEFAULT AS IDENTITY,
	country_id					text,
	"year"						integer,
	population					float8
);


create TABLE population_subnational_summary (
	id                          integer primary key GENERATED BY DEFAULT AS IDENTITY,
	country_id					text REFERENCES country(id),
	aggregation_area_id			text REFERENCES aggregation_area (gid),
	population_2021				float8,
	population_2022				float8,
	population_2023				float8,
	population_2024				float8,
	population_2025				float8,
	population_2026				float8,
	population_2027				float8,
	population_2028				float8,
	population_2029				float8,
	population_2030				float8,
	population_2031				float8,
	population_2032				float8,
	population_2033				float8,
	population_2034				float8,
	population_2035				float8,
	source						text
);

create or replace view intervention_projected_households as
select 
	pss.country_id,
	aa."name", 
	aa.admin_level, 
	pss.population_2021,
	pss.population_2022,
	pss.population_2023,
	pss.population_2024,
	pss.population_2025,
	pss.population_2026,
	pss.population_2027,
	pss.population_2028,
	pss.population_2029,
	pss.population_2030,
	pss.population_2031,
	pss.population_2032,
	pss.population_2033,
	pss.population_2034,
	pss.population_2035,
	pss.source
	
from population_subnational_summary pss 
join aggregation_area aa ON aa.gid = pss.aggregation_area_id 
order by pss.country_id, aa.admin_level, aa."name";