CREATE TABLE survey (
    id                             integer primary key generated by default as IDENTITY
    , name                         text
    , description                  text
    , publication_date             text
    , surveying_date_start         text
    , surveying_date_end           text
    , geometry                     geometry(MultiPolygon,4326)
    , geonetwork_uuid              text
    , survey_weight_factor         numeric
    , notes                        text
	, survey_type                  text CHECK (survey_type IN ('biomarker', 'food consumption'))
    , hb_is_adjusted_for_smoking   boolean
    , hb_is_adjusted_for_altitude  boolean
);

COMMENT ON TABLE survey IS 'Surveys that have been carried out and collected data from households on things including the households (or the individuals therein) food consumption';
COMMENT ON COLUMN survey.name                        IS 'The name of the survey';
COMMENT ON COLUMN survey.publication_date            IS 'The date when the survey was published';
COMMENT ON COLUMN survey.surveying_date_start        IS 'The date when surveying and interviewing started';
COMMENT ON COLUMN survey.surveying_date_end          IS 'The date when no further interviews took place';
COMMENT ON COLUMN survey.geometry                    IS 'The area covered by the survey; all households interviewed by the survey should fall into this area';
COMMENT ON COLUMN survey.geonetwork_uuid             IS 'a UUID for Geonetwork. See https://geonetwork-opensource.org/ for further info';
COMMENT ON COLUMN survey.survey_weight_factor        IS 'The factor survey weightings have been scaled by';
COMMENT ON COLUMN survey.notes                       IS 'a generic text field for notes about a survey. Can include such as: Whether biomarker measurements were taken from blood plasma or blood serum';
COMMENT ON COLUMN survey.hb_is_adjusted_for_smoking  IS 'Whether haemoglobin data is already adjusted per individual to account for whether the individual smokes';
COMMENT ON COLUMN survey.hb_is_adjusted_for_altitude IS 'Whether haemoglobin data is already adjusted per individual to account for whether the individual lives at high altitude';

