CREATE TABLE HOUSEHOLD_CONSUMPTION (
    id                     integer primary key GENERATED BY DEFAULT AS IDENTITY
    , fooditem_id          integer references fooditem (id)
    , household_member_id  integer references household_member (id)
    , date_consumed        date
    , amount_consumed_in_g numeric(20,10)

)
