CREATE TABLE household_member_consumption (
    id                     integer primary key GENERATED BY DEFAULT AS IDENTITY
    , foodex_id            text references foodex (id)
    , foodex_confidence    text references foodex_confidence (id)
    , household_member_id  integer references household_member (id)
    , source_of_food       text CHECK (source_of_food IN ('own production', 'bought', 'gifted/other'))
    , date_consumed        date
    , amount_consumed_in_g numeric(10,3)

);

COMMENT ON TABLE household_member_consumption IS 'What food items what been consumed by individual members of a household, and in what quantity.';
COMMENT on column household_member_consumption.foodex_id            IS 'The foodex id of the fooditem that was consumed';
COMMENT on column household_member_consumption.foodex_confidence    IS 'How confident we are in matching this food to the corresponding foodex entry';
COMMENT on column household_member_consumption.household_member_id  IS 'The id of the household member that consumed the food item';
COMMENT on column household_member_consumption.source_of_food       IS 'From where the household member obtained the food; if they grew it themselves, bought it at market, or had it gifted to them';
COMMENT on column household_member_consumption.date_consumed        IS 'The date when the fooditem was consumed';
COMMENT on column household_member_consumption.amount_consumed_in_g IS 'How much of the fooditem was consumed, in grams';
