CREATE TABLE BIOMARKER (
	id                        integer primary key GENERATED BY DEFAULT AS IDENTITY
    , household_member_id     integer REFERENCES household_member (id)
    , date_sampled            date
    , sample_type             text
    , Zinc_in_mcg             numeric(20,10)
);
COMMENT ON TABLE BIOMARKER IS '';
COMMENT ON COLUMN BIOMARKER.date_sampled IS 'The date when the sample was taken from the body';
COMMENT ON COLUMN BIOMARKER.sample_type IS 'Whether this is a urine or blood sample';
COMMENT ON COLUMN BIOMARKER.Zinc_in_mcg IS 'the amount of zinc in mcg per 10ml';


