
CREATE TABLE COUNTRY_CONSUMPTION (
    id                     integer primary key GENERATED BY DEFAULT AS IDENTITY
    , original_id          text
    , foodex_id            text references foodex (id)
    , foodex_confidence    text references foodex_confidence (id)
    , country_id           text    references country (id)
    , date_consumed        date
    , amount_consumed_in_g numeric(10,3)

);

COMMENT ON TABLE COUNTRY_CONSUMPTION IS 'What food items what been consumed per capita per year in a country, and in what quantity.';
COMMENT on column COUNTRY_CONSUMPTION.foodex_id            IS 'The food id of the fooditem that was consumed';
COMMENT on column COUNTRY_CONSUMPTION.originalx_id         IS 'The original name or id of the fooditem that was consumed';
COMMENT on column COUNTRY_CONSUMPTION.foodex_confidence    IS 'How confident we are in matching this food to the corresponding foodex entry';
COMMENT on column COUNTRY_CONSUMPTION.country_id           IS 'The id of the country that consumed the food item';
COMMENT on column COUNTRY_CONSUMPTION.date_consumed        IS 'The date when the fooditem was consumed';
COMMENT on column COUNTRY_CONSUMPTION.amount_consumed_in_g IS 'How much of the fooditem was consumed, in grams per capita';
