	CREATE TABLE fct_list_food_composition (
	    id 								integer primary key GENERATED BY DEFAULT AS identity,
	    fct_list_id 					integer,
	    food_genus_id 					text,
	    micronutrient_id               	text,
	    micronutrient_composition      	numeric,
	    fooditem_column					text,
	    fct_used            			integer,
		CONSTRAINT fct_list_food_composition_uk1 UNIQUE (fct_list_id, food_genus_id, micronutrient_id),
		   CONSTRAINT fct_list_food_composition_fk1
      FOREIGN KEY(fct_list_id) 
	  REFERENCES distinct_fct_list(id)
	);
