CREATE TABLE household_consumption (
    id                     integer primary key GENERATED BY DEFAULT AS IDENTITY
    , fooditem_id          integer references fooditem (id)
    , household_id         integer references household (id)
    , date_consumed        date
    , amount_consumed_in_g numeric(10,3)

);

COMMENT ON TABLE household_consumption IS 'What food items what been consumed by a household as a whole, and in what quantity.';
COMMENT on column household_consumption.fooditem_id          IS 'The id of the fooditem that was consumed';
COMMENT on column household_consumption.household_id         IS 'The id of the household that consumed the food item';
COMMENT on column household_consumption.date_consumed        IS 'The date when the fooditem was consumed';
COMMENT on column household_consumption.amount_consumed_in_g IS 'How much of the fooditem was consumed, in grams';
