CREATE TABLE household_member_consumption (
    id                     integer primary key GENERATED BY DEFAULT AS IDENTITY
    , fooditem_id          integer references fooditem (id)
    , household_member_id  integer references household_member (id)
    , date_consumed        date
    , amount_consumed_in_g numeric(10,3)

);

COMMENT ON TABLE household_member_consumption IS 'What food items what been consumed by individual members of a household, and in what quantity.';
COMMENT on column household_member_consumption.fooditem_id          IS 'The id of the fooditem that was consumed';
COMMENT on column household_member_consumption.household_member_id  IS 'The id of the household member that consumed the food item';
COMMENT on column household_member_consumption.date_consumed        IS 'The date when the fooditem was consumed';
COMMENT on column household_member_consumption.amount_consumed_in_g IS 'How much of the fooditem was consumed, in grams';
