CREATE TABLE biomarker_measurement (
	id                        integer primary key GENERATED BY DEFAULT AS IDENTITY
    , household_member_id     integer REFERENCES household_member (id)
    , date_sampled            date
    , sample_type             text
    , haemoglobin             numeric(5,2)
    , ferritin                numeric(5,2)
    , stfr                    numeric(3,2)
    , rbp                     numeric(3,2)
    , retinol                 numeric(3,2)
    , folate                  numeric(4,1)
    , vitamin_b12             numeric(5,1)
    , zinc                    numeric(3,1)
    , crp                     numeric(3,2)
    , agp                     numeric(3,2)
    , iodine                  numeric(5,2)
    , am_or_pm                text check (am_or_pm in ('am','pm') )
    , was_fasting             boolean

);
COMMENT ON TABLE  Biomarker_measurement IS 'Levels of various biomarkers as measured by sampling blood, urine, or breastmilk from a household member';
COMMENT ON COLUMN Biomarker_measurement.household_member_id IS 'The id of the household member from which the blood, urine, or breastmilk sample was taken';
COMMENT ON COLUMN Biomarker_measurement.date_sampled     IS 'The date when the sample was taken from the body';
COMMENT ON COLUMN Biomarker_measurement.sample_type      IS 'Whether this is a urine, blood, or breastmilk sample';
COMMENT ON COLUMN Biomarker_measurement.haemoglobin      IS 'The amount of haemoglbin (also known as hemoglobin) in the blood, in grams per litre.';
COMMENT ON COLUMN Biomarker_measurement.ferritin         IS 'The amount of Serum Ferritn found in the blood, in micrograms per litre';
COMMENT ON COLUMN Biomarker_measurement.stfr             IS 'The amount of Soluble Transferrin Receptors (sTfR) in the blood, in milligrams per litre';
COMMENT ON COLUMN Biomarker_measurement.rbp              IS 'The amount of Retinol Binding Protein (RBP) in the blood, in micromoles per litre';
COMMENT ON COLUMN Biomarker_measurement.retinol          IS 'The amount of Retinol in the blood, in micromoles per litre';
COMMENT ON COLUMN Biomarker_measurement.folate           IS 'The amount of Folate in the blood, in nanomoles per litre';
COMMENT ON COLUMN Biomarker_measurement.vitamin_b12      IS 'The amount of Vitamin B12 (also known as cobalamin) in the blood, in picomoles per litre';
COMMENT ON COLUMN Biomarker_measurement.zinc             IS 'The amount of plasma or serum zinc, in micrograms per decilitre';
COMMENT ON COLUMN Biomarker_measurement.crp              IS 'The amount of C-reactive protein (CRP) in the blood, in milligrams per litre. A value ≥5 defines inflammation';
COMMENT ON COLUMN Biomarker_measurement.agp              IS 'The amount of Alpha 1 acid GlycoProtein (AGO) in the blood, in grams per litre. A value ≥1 defines inflammation';
COMMENT ON COLUMN Biomarker_measurement.iodine           IS 'The amount of Urinary Iodine, in micrograms per litre. ';
COMMENT ON COLUMN Biomarker_measurement.am_or_pm         IS 'Whether the measurement was taken in the morning or afternoon (pre or post noon local time)';
COMMENT ON COLUMN Biomarker_measurement.was_fasting      IS 'Whether the sample was taken while the patient was fasting';
