CREATE TABLE household_intake_static (
	survey_id int4 NULL,
	household_id int8 NULL,
	fct_source_id int4 NULL,
	aggregation_area_id int4 NULL,
	aggregation_area_name text NULL,
	aggregation_area_type text NULL,
	vitamina_in_rae_in_mcg numeric NULL,
	vitaminb6_in_mg numeric NULL,
	vitaminb12_in_mcg numeric NULL,
	vitaminc_in_mg numeric NULL,
	vitamind_in_mcg numeric NULL,
	vitamine_in_mg numeric NULL,
	thiamin_in_mg numeric NULL,
	riboflavin_in_mg numeric NULL,
	niacin_in_mg numeric NULL,
	folicacid_in_mcg numeric NULL,
	folate_in_mcg numeric NULL,
	pantothenate_in_mg numeric NULL,
	biotin_in_mcg numeric NULL,
	phytate_in_mg numeric NULL,
	ca_in_mg numeric NULL,
	cu_in_mg numeric NULL,
	fe_in_mg numeric NULL,
	mg_in_mg numeric NULL,
	mn_in_mcg numeric NULL,
	p_in_mg numeric NULL,
	k_in_mg numeric NULL,
	na_in_mg numeric NULL,
	zn_in_mg numeric NULL,
	i_in_mcg numeric NULL,
	nitrogen_in_g numeric NULL,
	se_in_mcg numeric NULL,
	ash_in_g numeric NULL,
	fibre_in_g numeric NULL,
	carbohydrates_in_g numeric NULL,
	cholesterol_in_mg numeric NULL,
	totalprotein_in_g numeric NULL,
	totalfats_in_g numeric NULL,
	energy_in_kcal numeric NULL,
	moisture_in_g numeric NULL,
	energy_in_kj numeric NULL,
	monounsaturatedfa_in_g numeric NULL,
	polyunsaturatedfa_in_g numeric NULL,
	saturatedfa_in_g numeric NULL
);
;

COMMENT ON VIEW household_intake IS 'View of amount of micronutrients consumed in total by individual households ';
