
--
-- TABLE: data_source
--

CREATE TABLE data_source(
    data_source_id    integer   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    data_source       text,
    CONSTRAINT "data_source_pk" PRIMARY KEY (data_source_id)
)
;

