--
-- TABLE: fortification_level
--

CREATE TABLE fortification_level(
    fortification_level_id    integer   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    micronutrient_id          text,
    compound_id               text,
    intervention_id           integer,
    target_level              numeric,
    practice_level            numeric,
    input_source              text,
    CONSTRAINT "fortification_level_pk" PRIMARY KEY (fortification_level_id)
)
;

--
-- TABLE: fortification_level
--

ALTER TABLE fortification_level ADD CONSTRAINT "Refmicronutrient111"
    FOREIGN KEY (micronutrient_id)
    REFERENCES micronutrient(micronutrient_id)
;

ALTER TABLE fortification_level ADD CONSTRAINT "Reffortification_compound121"
    FOREIGN KEY (compound_id)
    REFERENCES fortification_compound(compound_id)
;

ALTER TABLE fortification_level ADD CONSTRAINT "Refintervention131"
    FOREIGN KEY (intervention_id)
    REFERENCES intervention(intervention_id)
;
