CREATE TABLE fortificant(
    id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             text,
    micronutrient_id TEXT REFERENCES micronutrient(id),
    mn_percent       numeric
)
;


