
CREATE TABLE intervention_variable(
    variable_id               integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , variable_text           text
    , intervention_id         integer     NOT NULL REFERENCES intervention(intervention_id)
    , notes                   text
    , display_heading_id      integer              REFERENCES display_heading(display_heading_id)
    , display_sub_heading_id  integer              REFERENCES display_sub_heading(display_sub_heading_id)
    , CONSTRAINT "intervention_variable_pk" PRIMARY KEY (variable_id)
)
;


