

CREATE TABLE factor_value(
    id                       integer PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    intervention_id          integer REFERENCES intervention(id),
    value                    numeric,
    intervention_factor_id   integer    NOT NULL REFERENCES intervention_factor(id),
    year                     integer
)
;

