
CREATE TABLE variable_type(
    id                    integer PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    text                  text,
    intervention_id       integer    NOT NULL REFERENCES intervention(id)
)
;

