
CREATE TABLE baseline_assumption(
    id      integer PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name    text,
    intervention_id    integer    NOT NULL REFERENCES intervention(id)
)
;

