--
-- TABLE: variable_value
--

CREATE TABLE variable_value(
    variable_value_id    integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    variable_value       numeric,
    units                text,
    variable_id          integer    NOT NULL,
    year                 integer    NOT NULL,
    intervention_source_id       integer,
    CONSTRAINT "variable_value_pk" PRIMARY KEY (variable_value_id)
)
;

--
-- TABLE: variable_value
--

ALTER TABLE variable_value ADD CONSTRAINT "Refintervention_variable201"
    FOREIGN KEY (variable_id)
    REFERENCES intervention_variable(variable_id)
;

ALTER TABLE variable_value ADD CONSTRAINT "Refyear211"
    FOREIGN KEY (year)
    REFERENCES year(year)
;

ALTER TABLE variable_value ADD CONSTRAINT "Refdata_source231"
    FOREIGN KEY (intervention_source_id)
    REFERENCES intervention_source(id)
;

