

create table impact_projections
(id                 integer primary key GENERATED BY DEFAULT AS identity,
file_name           text,
row_index           integer,
food_vehicle_id	    integer REFERENCES food_vehicle (id),
year_0              numeric,
year_1              numeric,
year_2              numeric,
year_3              numeric,
year_4              numeric,
year_5              numeric,
year_6              numeric,
year_7              numeric,
year_8              numeric,
year_9              numeric,
source              text);

comment on table impact_projections is 'A table to store the data in IMPACT projections worksheets included in intervention costings excel files';