
--drop table intervention_data;

create table intervention_data
(
id                  integer primary key GENERATED BY DEFAULT AS identity,
intervention_id     integer REFERENCES intervention (id),
row_index           integer,
row_name            text,
header1             text,
header2             text,
factor_text         text,
formula_index       text,
year_0              numeric,
year_1              numeric,
year_2              numeric,
year_3              numeric,
year_4              numeric,
year_5              numeric,
year_6              numeric,
year_7              numeric,
year_8              numeric,
year_9              numeric,
notes               text
);

COMMENT on table intervention_data is 'Table to store data directly loaded from excel spreadsheet costing models';