
CREATE TABLE intervention_variable(
    id                        integer     PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , variable_text           text
    , intervention_id         integer     NOT NULL REFERENCES intervention(id)
    , notes                   text
    , display_heading_id      integer              REFERENCES display_heading(id)
    , display_sub_heading_id  integer              REFERENCES display_sub_heading(id)
)
;


