
CREATE TABLE intervention_factor (
    id                        integer     PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , label                   text
    , food_vehicle_id         integer     NOT NULL REFERENCES food_vehicle(id)
    , formula_index           integer
    , notes                   text
    , display_heading_id      integer              REFERENCES display_heading(id)
    , display_sub_heading_id  integer              REFERENCES display_sub_heading(id)
)
;


COMMENT ON table intervention_factor is '';
COMMENT ON column intervention_factor.formula_index is 'id so that the frontend knows which values to to multply together and which to add together regardless of food vehicle e.g. formula index 1 might refer to the number of factories in a country - for what flour they are referrred to as mills while for oil they are referred to as refineries, but they are both multiplied with other factors in the same way';
