--
-- TABLE: intervention
--

CREATE TABLE intervention(
    id                           integer  PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    intervention_name            text,
    country_id                   text       REFERENCES country(id),
    app_user_id                  text       REFERENCES app_user(id),
    intervention_source_id       integer    REFERENCES intervention_source(id),
    food_vehicle_id              numeric    REFERENCES food_vehicle(id),
    intervention_type_id         text       REFERENCES intervention_type(id),
    program_status               text,
    is_premade                   boolean
)
;

COMMENT on column intervention.is_premade is 'Whether this intervention is pre-created by professionals, or whether this is an intervention where an end-user has customised some values';

