

CREATE TABLE variable_value(
    id                       integer PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    variable_value           numeric,
    units                    text,
    variable_id              integer    NOT NULL REFERENCES intervention_variable(id),
    year                     integer    NOT NULL REFERENCES year(year),
    intervention_source_id   integer REFERENCES intervention_source(id)
)
;

