--
-- TABLE: fortification_level
--

CREATE TABLE fortification_level(
    id                        integer   PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    micronutrient_id          text      REFERENCES micronutrient(id),
    compound_id               text      REFERENCES fortification_compound(id),
    intervention_id           integer   REFERENCES intervention(id),
    target_level              numeric,
    practice_level            numeric,
    input_source              text
)
;

