CREATE TABLE data_citation(
    id    integer   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    short_text                text,
    citation_text             text,
    CONSTRAINT "intervention_source_pk" PRIMARY KEY (id)
)
;

COMMENT ON table data_citation IS 'The citation data of the data that the default data is based on e.g. according to the Global Fortification Data Exchange a biofortification program in country X uses this many millilitres of fortification solution per wheat flour mill';
COMMENT ON COLUMN data_citation.short_text IS 'A short name for the source of the data. Will be used as a label in the UI, and should thus be kept short';
COMMENT ON COLUMN data_citation.citation_text IS 'The full name/citation text for the publication that we got costings data from. Will be displayed as part of a bibliography, and can thus be as long as needed';
