CREATE TABLE fortificant(
    id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             text,
    micronutrient_id TEXT REFERENCES micronutrient(id),
    mn_percent       numeric
)
;

COMMENT ON TABLE fortificant IS 'List of fortificants (substances that get added to food to fortify it with nutrients), including which nutrient they fortify and what proportion of the fortificant can be assumed to be the actual micronutrient';

COMMENT ON COLUMN fortificant.name IS 'Name of the fortificant, as take from Katy Adam''s spreadsheets';
COMMENT ON COLUMN fortificant.micronutrient_id IS 'What micronutrient this fortificant cotnains';
COMMENT ON COLUMN fortificant.mn_percent IS 'What percent of this fortificant is composed of the actual micronutrient, rather than filler or non-active ingredients';
