
--
-- TABLE: variable_type
--

CREATE TABLE variable_type(
    variable_type_id      integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    variable_type_text    text,
    intervention_id       integer    NOT NULL,
    CONSTRAINT "variable_type_pk" PRIMARY KEY (variable_type_id)
)
;

--
-- TABLE: variable_type
--

ALTER TABLE variable_type ADD CONSTRAINT "Refintervention321"
    FOREIGN KEY (intervention_id)
    REFERENCES intervention(intervention_id)
;
