CREATE TABLE expected_losses (
    id                     integer primary key generated by default as IDENTITY
    , food_vehicle_id      integer references food_vehicle (id)
    , micronutrient        text references micronutrient (id)
    , expected_losses      integer 
    , source               text
    CHECK (expected_losses BETWEEN 0 AND 1)
);

COMMENT ON TABLE expected_losses IS 'Default expected losses from point of fortification to households (%)';
COMMENT on column expected_losses.food_vehicle_id  IS 'The food vehicle which is fortified.  References the food_vehicle table';
COMMENT on column expected_losses.micronutrient    IS 'The micronutrient. References the micronutrient table';
COMMENT on column expected_losses.expected_losses IS 'The percentage expected loss.  Between 0 and 1';
COMMENT on column expected_losses.source           IS 'The source for the expected loss data';