--
-- TABLE: intervention
--

CREATE TABLE intervention(
    intervention_id      integer    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    intervention_name    text,
    country_id           text,
    user_id              text    REFERENCES country(id),
    data_source_id       integer,
    vehicle_id           text,
    status               text,
    type_id              text,
    program_status_id    text,
    CONSTRAINT "intervention_pk" PRIMARY KEY (intervention_id)
)
;


--
-- TABLE: intervention
--


ALTER TABLE intervention ADD CONSTRAINT "Refuser21"
    FOREIGN KEY (user_id)
    REFERENCES app_user(id)
;

ALTER TABLE intervention ADD CONSTRAINT "Refdata_source171"
    FOREIGN KEY (data_source_id)
    REFERENCES data_source(data_source_id)
;

ALTER TABLE intervention ADD CONSTRAINT "Reffood_vehicle181"
    FOREIGN KEY (vehicle_id)
    REFERENCES food_vehicle(vehicle_id)
;

ALTER TABLE intervention ADD CONSTRAINT "Refintervention_type221"
    FOREIGN KEY (type_id)
    REFERENCES intervention_type(type_id)
;
