create table display_sub_heading(
	display_sub_heading_id   integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	display_sub_heading_text text,
	constraint "display_sub_heading_pk" primary key (display_sub_heading_id)
)
;
