CREATE TABLE intervention_extra_costs(
    id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    intervention_id  integer REFERENCES intervention(id),
    cost_type        text CHECK (cost_type IN ('susu', 'recurring')),
    factor_text      text,
    year_0           numeric,
    year_1           numeric,
    year_2           numeric,
    year_3           numeric,
    year_4           numeric,
    year_5           numeric,
    year_6           numeric,
    year_7           numeric,
    year_8           numeric,
    year_9           numeric,
    mn_percent       numeric
)
;

COMMENT ON TABLE intervention_extra_costs IS 'Table to store additional user costs for a given intervention';
