CREATE TABLE DATA_REFERENCE (
	id                            integer primary key GENERATED BY DEFAULT AS IDENTITY
	, fct_source_id               integer references FCT_SOURCE (ID)
	, original_id                 text
	, name                        text
	, author                      text
	, publication                 text
	, isbn                        text
	, notes                       text
);
COMMENT ON TABLE DATA_REFERENCE IS 'Table of bibliographic references. These references indicate from which publication the food composition data was taken';
COMMENT ON COLUMN DATA_REFERENCE.original_id IS 'The id of the referece as it appears in the original data';
Comment on COLUMN DATA_REFERENCE.fct_source_id IS 'The ID of the Food Composition Table where the reference appeared';

