CREATE TABLE FOOD_GROUP (
	id               integer primary key GENERATED BY DEFAULT AS IDENTITY
	, name           text unique
);

INSERT INTO FOOD_GROUP (id, name)
VALUES
	(1, 'Cereals')
	, (2, 'Roots, tubers, plantains')
	, (3, 'Pulses, seeds and nuts')
	, (4, 'Milk')
	, (5, 'Eggs')
	, (6, 'Fish, shellfish')
	, (7, 'Meat')
	, (8, 'Insects, grubs')
	, (9, 'Vegetables')
	, (10, 'Fruits')
	, (11, 'Fats and oils')
	, (12, 'Sweets and sugars')
	, (13, 'Spices and condiments')
	, (14, 'Beverages')
	, (15, 'Savoury snacks')
	, (16, 'Other')
	, (101,	'Animal')
	, (102, 'Baby food')
	, (103, 'Fats and oil')
	, (104, 'Fruit')
	, (105, 'Legume')
	, (106, 'Miscellaneous')
	, (107, 'Staple')
	, (108, 'Vegetable')
;
