CREATE TABLE FOOD_GROUP (
	id               integer primary key GENERATED BY DEFAULT AS IDENTITY
    (START WITH 2000 INCREMENT BY 1)
	, name           text unique
    , parent_id      integer REFERENCES FOOD_GROUP (id)
);

INSERT INTO FOOD_GROUP (id, parent_id, name)
VALUES
    (1,1, 'Cereals and their products')
    , (101,1,'Rice and rice-based products')
    , (102,1,'Maize and maize-based products')
    , (103,1,'Wheat and wheat-based products')
    ,(2,2, 'Roots, tubers, plantains and their products')
    , (201,2, 'Potato, sweet potato and their products')
    , (202,2, 'Cassava and similar roots (excluding taro) and their products')
    ,(3,3, 'Pulses, seeds and nuts and their products')
    , (301,3, 'Pulses (excluding soybeans) and their products')
    ,(4,4, 'Milk and milk products')
    , (401,4, 'Milk: fresh and processed')
    , (402,4, 'Fermented milk products')
    , (403,4, ' Cream, whey and any other milk products excluding fermented milk products and cheese')
    , (404,4, ' Cheese')
    ,(5,5, 'Eggs and their products')
    ,(6,6, 'Fish, shellfish and their products')
    , (601,6, 'Freshwater fish (excluding offal)')
    ,(7,7, 'Meat and meat products')
    , (701,7, 'Offal - all types')
    , (702,7, 'Mammals, reptiles and amphibians (excluding offal)')
    ,(8,8, 'Insects, grubs and their products')
    ,(9,9, 'Vegetables and their products')
    ,(10,10, 'Fruits and their products')
    , (1002,10, 'Fruits: fresh')
    ,(11,11, 'Fats and oils')
    ,(12,12, 'Sweets and sugars')
    ,(13,13, 'Spices and condiments')
    ,(14,14, 'Beverages')
    ,(15,15, 'Foods for particular nutritional uses')
    ,(17,17, 'Food additives')
    ,(18,18, 'Composite dishes')
    ,(19,19, 'Savoury snacks')
;

COMMENT ON TABLE food_group IS 'List of top-level and subgroup FAO (Food and Agriculture Organisation of the United Nations) food groups for a food_genus item. See http://www.fao.org/gift-individual-food-consumption/methodology/food-groups-and-sub-groups/en/';
