CREATE TABLE FOOD_GROUP (
	id               integer primary key GENERATED BY DEFAULT AS IDENTITY
	, name           text unique
    , parent_id      integer REFERENCES FOOD_GROUP (id)
);

INSERT INTO FOOD_GROUP (id, parent_id, name)
VALUES
	(1, 1, 'Cereals')
	, (2, 2, 'Roots, tubers, plantains')
	, (3, 3, 'Pulses, seeds and nuts')
	, (4, 4, 'Milk')
	, (5, 5, 'Eggs')
	, (6, 6, 'Fish, shellfish')
	, (7, 7, 'Meat')
	, (8, 8, 'Insects, grubs')
	, (9, 9, 'Vegetables')
	, (10, 10, 'Fruits')
	, (11, 11, 'Fats and oils')
	, (12, 12, 'Sweets and sugars')
	, (13, 13, 'Spices and condiments')
	, (14, 14, 'Beverages')
	, (15, 15, 'Savoury snacks')
	, (16, 16, 'Other')
	, (101,	101, 'Animal')
	, (102, 102, 'Baby food')
	, (103, 103, 'Fats and oil')
	, (104, 104, 'Fruit')
	, (105, 105, 'Legume')
	, (106, 106, 'Miscellaneous')
	, (107, 107, 'Staple')
	, (108, 108, 'Vegetable')
;

COMMENT ON TABLE food_group IS 'List of top-level and subgroup FAO (Food and Agriculture Organisation of the United Nations) food groups for a food_genus item. See http://www.fao.org/gift-individual-food-consumption/methodology/food-groups-and-sub-groups/en/';
