CREATE TABLE FOOD_GROUP (
	id               integer primary key GENERATED BY DEFAULT AS IDENTITY
	, name           text unique
);

INSERT INTO FOOD_GROUP (name)
VALUES
	('Animal')
	, ('Baby food')
	, ('Fats and oil')
	, ('Fruit')
	, ('Legume')
	, ('Miscellaneous')
	, ('Staple')
	, ('Vegetable')
;
