CREATE TABLE survey_group_def (
survey_group_def_id integer primary key GENERATED BY DEFAULT AS IDENTITY,
survey_id           integer REFERENCES survey (id),
group_id            text REFERENCES biomarker_group (group_id),
sex text CHECK (sex IN ('m','f','both')),
age_lower_in_months numeric,
age_upper_in_months numeric
);

COMMENT ON TABLE survey_group_def IS 'Table of group definitions specific to a survey.';
COMMENT on column survey_group_def.survey_group_def_id is 'Primary key identifier for the survey group definition';
COMMENT on column survey_group_def.survey_id is 'Foreign key reference to the survey table';
COMMENT on column survey_group_def.group_id is 'Foreign key reference to the biomarker_group table';
COMMENT on column survey_group_def.sex is 'Gender for which the threshold applies';
COMMENT on column survey_group_def.age_lower_in_months is 'Lower age for which the threshold applies';
COMMENT on column survey_group_def.age_upper_in_months is 'Upper age for which the threshold applies if any';
