Create Table region (
      id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    , name        TEXT
);

COMMENT ON TABLE region IS 'geographic regions (specifically a mix of intermediate and sub regions) as used by the World Health Organisation methodology Standard country or area codes for statistical use (M49). see https://unstats.un.org/unsd/methodology/m49/ and https://en.m.wikipedia.org/wiki/United_Nations_geoscheme_for_Africa';
