

--
-- TABLE: baseline_ass_val
--

CREATE TABLE baseline_ass_val(
    assumption_id      integer    NOT NULL,
    intervention_id    integer    NOT NULL,
    year               integer    NOT NULL,
    value              numeric,
    CONSTRAINT "baseline_ass_val_pk" PRIMARY KEY (assumption_id, intervention_id)
)
;



--
-- TABLE: baseline_assumption
--

CREATE TABLE baseline_assumption(
    assumption_id      integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    assumption_name    text,
    intervention_id    integer    NOT NULL,
    CONSTRAINT "baseline_assumption_pk" PRIMARY KEY (assumption_id)
)
;



--
-- TABLE: country
--

CREATE TABLE country(
    country_id    text   NOT NULL,
    country_name       text,
    CONSTRAINT "country_pk" PRIMARY KEY (country_id)
)
;



--
-- TABLE: data_source
--

CREATE TABLE data_source(
    data_source_id    integer   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    data_source       text,
    CONSTRAINT "data_source_pk" PRIMARY KEY (data_source_id)
)
;



--
-- TABLE: expected_loss
--

CREATE TABLE expected_loss(
    micronutrient_id    text    NOT NULL,
    intervention_id     integer    NOT NULL,
    expected_loss_pc    numeric,
    CONSTRAINT "expected_loss_pk" PRIMARY KEY (micronutrient_id, intervention_id)
)
;



--
-- TABLE: food_vehicle
--

CREATE TABLE food_vehicle(
    vehicle_id      text    NOT NULL,
    vehicle_name    text,
    CONSTRAINT "food_vehicle_pk" PRIMARY KEY (vehicle_id)
)
;



--
-- TABLE: fortification_compound
--

CREATE TABLE fortification_compound(
    compound_id     text    NOT NULL,
    compund_name    text,
    CONSTRAINT "fortification_compound_pk" PRIMARY KEY (compound_id)
)
;



--
-- TABLE: fortification_level
--

CREATE TABLE fortification_level(
    fortification_level_id    integer   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    micronutrient_id          text,
    compound_id               text,
    intervention_id           integer,
    target_level              numeric,
    practice_level            numeric,
    input_source              text,
    CONSTRAINT "fortification_level_pk" PRIMARY KEY (fortification_level_id)
)
;



--
-- TABLE: intervention
--

CREATE TABLE intervention(
    intervention_id      integer    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    intervention_name    text,
    country_id           text,
    user_id              text,
    data_source_id       integer,
    vehicle_id           text,
    status               text,
    type_id              text,
    program_status_id    text,
    CONSTRAINT "intervention_pk" PRIMARY KEY (intervention_id)
)
;



--
-- TABLE: intervention_type
--

CREATE TABLE intervention_type(
    type_id              text    NOT NULL,
    intervention_type    text,
    CONSTRAINT "intervention_type_pk" PRIMARY KEY (type_id)
)
;


create table display_heading(
	display_heading_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	display_heading_text text,
	constraint "display_heading_pk" primary key (display_heading_id)
)
;
create table display_sub_heading(
	display_sub_heading_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	display_sub_heading_text text,
	constraint "display_sub_heading_pk" primary key (display_sub_heading_id)
)
;

--
-- TABLE: intervention_variable
--

CREATE TABLE intervention_variable(
    variable_id         integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    variable_text       text,
    intervention_id     integer    NOT NULL,
    notes               text,
    formula_type        text,
    display_heading_id integer,
    display_sub_heading_id integer,
    CONSTRAINT "intervention_variable_pk" PRIMARY KEY (variable_id)
)
;



--
-- TABLE: micronutrient
--

CREATE TABLE micronutrient(
    micronutrient_id    text    NOT NULL,
    name                text,
    category            text,
    CONSTRAINT "micronutrient_pk" PRIMARY KEY (micronutrient_id)
)
;



--
-- TABLE: user
--

CREATE TABLE bmgf_user(
    user_id      text    NOT NULL,
    user_name    text,
    CONSTRAINT "bmgf_user_pk" PRIMARY KEY (user_id)
)
;



--
-- TABLE: variable_type
--

CREATE TABLE variable_type(
    variable_type_id      integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    variable_type_text    text,
    intervention_id       integer    NOT NULL,
    CONSTRAINT "variable_type_pk" PRIMARY KEY (variable_type_id)
)
;



--
-- TABLE: variable_value
--

CREATE TABLE variable_value(
    variable_value_id    integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    variable_value       numeric,
    units                text,
    variable_id          integer    NOT NULL,
    year                 integer    NOT NULL,
    data_source_id       integer,
    CONSTRAINT "variable_value_pk" PRIMARY KEY (variable_value_id)
)
;



--
-- TABLE: year
--

CREATE TABLE year(
    year    integer    NOT NULL,
    CONSTRAINT "year_pk" PRIMARY KEY (year)
)
;

-- TABLE: program_status

create table program_status(
	program_status_id text not null,
	program_status_description text,
	CONSTRAINT "program_status_pk" PRIMARY KEY (program_status_id)
)
;

--
-- TABLE: baseline_ass_val
--

ALTER TABLE baseline_ass_val ADD CONSTRAINT "Refbaseline_assumption91"
    FOREIGN KEY (assumption_id)
    REFERENCES baseline_assumption(assumption_id)
;

ALTER TABLE baseline_ass_val ADD CONSTRAINT "Refintervention101"
    FOREIGN KEY (intervention_id)
    REFERENCES intervention(intervention_id)
;

ALTER TABLE baseline_ass_val ADD CONSTRAINT "Refyear141"
    FOREIGN KEY (year)
    REFERENCES year(year)
;


--
-- TABLE: baseline_assumption
--

ALTER TABLE baseline_assumption ADD CONSTRAINT "Refintervention341"
    FOREIGN KEY (intervention_id)
    REFERENCES intervention(intervention_id)
;


--
-- TABLE: expected_loss
--

ALTER TABLE expected_loss ADD CONSTRAINT "Refmicronutrient151"
    FOREIGN KEY (micronutrient_id)
    REFERENCES micronutrient(micronutrient_id)
;

ALTER TABLE expected_loss ADD CONSTRAINT "Refintervention161"
    FOREIGN KEY (intervention_id)
    REFERENCES intervention(intervention_id)
;


--
-- TABLE: fortification_level
--

ALTER TABLE fortification_level ADD CONSTRAINT "Refmicronutrient111"
    FOREIGN KEY (micronutrient_id)
    REFERENCES micronutrient(micronutrient_id)
;

ALTER TABLE fortification_level ADD CONSTRAINT "Reffortification_compound121"
    FOREIGN KEY (compound_id)
    REFERENCES fortification_compound(compound_id)
;

ALTER TABLE fortification_level ADD CONSTRAINT "Refintervention131"
    FOREIGN KEY (intervention_id)
    REFERENCES intervention(intervention_id)
;


--
-- TABLE: intervention
--

ALTER TABLE intervention ADD CONSTRAINT "Refcountry11"
    FOREIGN KEY (country_id)
    REFERENCES country(country_id)
;

ALTER TABLE intervention ADD CONSTRAINT "Refuser21"
    FOREIGN KEY (user_id)
    REFERENCES bmgf_user(user_id)
;

ALTER TABLE intervention ADD CONSTRAINT "Refdata_source171"
    FOREIGN KEY (data_source_id)
    REFERENCES data_source(data_source_id)
;

ALTER TABLE intervention ADD CONSTRAINT "Reffood_vehicle181"
    FOREIGN KEY (vehicle_id)
    REFERENCES food_vehicle(vehicle_id)
;

ALTER TABLE intervention ADD CONSTRAINT "Refintervention_type221"
    FOREIGN KEY (type_id)
    REFERENCES intervention_type(type_id)
;


--
-- TABLE: intervention_variable
--

ALTER TABLE intervention_variable ADD CONSTRAINT "Refintervention331"
    FOREIGN KEY (intervention_id)
    REFERENCES intervention(intervention_id)
;

ALTER TABLE intervention_variable ADD CONSTRAINT "intervention_variable_fk1"
    FOREIGN KEY (display_heading_id)
    REFERENCES display_heading(display_heading_id)
;


--
-- TABLE: variable_type
--

ALTER TABLE variable_type ADD CONSTRAINT "Refintervention321"
    FOREIGN KEY (intervention_id)
    REFERENCES intervention(intervention_id)
;


--
-- TABLE: variable_value
--

ALTER TABLE variable_value ADD CONSTRAINT "Refintervention_variable201"
    FOREIGN KEY (variable_id)
    REFERENCES intervention_variable(variable_id)
;

ALTER TABLE variable_value ADD CONSTRAINT "Refyear211"
    FOREIGN KEY (year)
    REFERENCES year(year)
;

ALTER TABLE variable_value ADD CONSTRAINT "Refdata_source231"
    FOREIGN KEY (data_source_id)
    REFERENCES data_source(data_source_id)
;


