CREATE TABLE FOODITEM (
	id                               integer primary key GENERATED BY DEFAULT AS IDENTITY
    (START WITH 10000 INCREMENT BY 1)
	, Original_Food_Id               text
	, Original_Food_Name             text
	, food_genus_id                  text REFERENCEs food_genus (id)
	, food_genus_confidence          text REFERENCES food_genus_confidence (id)
    , FCT_SOURCE_ID                  integer REFERENCES FCT_SOURCE (ID)
	, citation_id                    text
	, Moisture_in_g                  numeric
	, Energy_in_kCal                 numeric
	, Energy_in_kJ                   numeric
	, Nitrogen_in_g                  numeric
	, TotalProtein_in_g              numeric
	, TotalFats_in_g                 numeric
	, SaturatedFA_in_g               numeric
	, MonounsaturatedFA_in_g         numeric
	, PolyunsaturatedFA_in_g         numeric
	, Cholesterol_in_mg              numeric
	, carbohydrates_in_g             numeric
	, Fibre_in_g                     numeric
	, Ash_in_g                       numeric
	, Ca_in_mg                       numeric
	, Fe_in_mg                       numeric
	, Mg_in_mg                       numeric
	, P_in_mg                        numeric
	, K_in_mg                        numeric
	, Na_in_mg                       numeric
	, Zn_in_mg                       numeric
	, Cu_in_mg                       numeric
	, Mn_in_mcg                      numeric
	, I_in_mcg                       numeric
	, Se_in_mcg                      numeric
	, VitaminA_in_RAE_in_mcg         numeric
	, Thiamin_in_mg                  numeric
	, Riboflavin_in_mg               numeric
	, Niacin_in_mg                   numeric
	, VitaminB6_in_mg                numeric
	, Folicacid_in_mcg               numeric
	, Folate_in_mcg                  numeric
	, VitaminB12_in_mcg              numeric
	, Pantothenate_in_mg             numeric
	, Biotin_in_mcg                  numeric
	, VitaminC_in_mg                 numeric
	, VitaminD_in_mcg                numeric
	, VitaminE_in_mg                 numeric
	, PhyticAcid_in_mg               numeric
);
