CREATE TABLE biomarker_region (
    id                                   integer primary key GENERATED BY DEFAULT AS identity
    , survey_id                          integer REFERENCES survey (id)
    , name                               text
    , aggregation_area                   integer REFERENCES aggregation_area(id)
);

CREATE OR REPLACE VIEW biomarker_aggregation_area as (
    select 
        survey_id
        , br.name
        , ST_UNION(geometry) as geometry
    FROM 
    	biomarker_region br
    join aggregation_area aa on aa.id = br.aggregation_area 
    group by 
        survey_id,
        br.name
);