CREATE TABLE biomarker_threshold (
    threshold_id                         integer primary key GENERATED BY DEFAULT AS identity
    , biomarker_id                       text REFERENCES biomarker (id)
    , group_id                           text REFERENCES biomarker_group (group_id)
    , conditional_info                   text
    , threshold_type                     text CHECK (threshold_type IN ('deficiency', 'excess', 'deficiency - mild', 'deficiency - moderate', 'deficiency - severe'))
    , source                             text
    , matrix                             text CHECK (matrix IN ('Plasma or Serum', 'Red blood cell', 'Whole blood'))
    , lower_threshold                    numeric
    , upper_threshold                    numeric
    , condition_time_of_day_sampled      text
    , condition_was_fasting              boolean
    , condition_age_in_months            integer
    , condition_sex                      text
    , condition_is_adjusted_for_smoking  boolean
    , condition_is_adjusted_for_altitude boolean
    , comments                           text
);

COMMENT ON TABLE biomarker_threshold IS 'Table of thresholds below which deficiency is indicated for the assigned biomarker and demographic';
COMMENT on column biomarker_threshold.threshold_id     is 'The threshold primary key identifier';
COMMENT on column biomarker_threshold.biomarker_id     is 'Foreign key reference to the biomarker table';
COMMENT on column biomarker_threshold.group_id         is 'Foreign key reference to the group table';
COMMENT on column biomarker_threshold.conditional_info is 'The condition(s) on which the threshold is applied';
COMMENT on column biomarker_threshold.threshold_type   is 'Whether a lower or upper biologically desirable MN threshold';
COMMENT on column biomarker_threshold.source           is 'Literature source from which data is derived';
COMMENT on column biomarker_threshold.matrix           is 'Biomarker sample matrix';
COMMENT on column biomarker_threshold.lower_threshold  is 'Value of the lower threshold for th is biomarker type';
COMMENT on column biomarker_threshold.upper_threshold  is 'Value of the upper threshold for th is biomarker type';
COMMENT on column biomarker_threshold.comments         is 'Any additional comments about the threshold';
COMMENT on column biomarker_threshold.condition_time_of_day_sampled        is 'Required value of the time_of_day_sampled field for the threshold to be applicable';
COMMENT on column biomarker_threshold.condition_was_fasting                is 'Required value of the was_fasting field for the threshold to be applicable';
COMMENT on column biomarker_threshold.condition_age_in_months              is 'Required value of the age_in_months field for the threshold to be applicable';
COMMENT on column biomarker_threshold.condition_sex                        is 'Required value of the sex field for the threshold to be applicable';


