CREATE TABLE biomarker_measurement (
	id                        integer primary key GENERATED BY DEFAULT AS IDENTITY
    , household_member_id     integer REFERENCES household_member (id)
    , date_sampled            date
    , sample_type             text
    , haemoglobin             numeric
    , ferritin                numeric
    , stfr                    numeric
    , rbp                     numeric
    , retinol                 numeric
    , rbc_folate              numeric
    , ps_folate               numeric
    , vitamin_b12             numeric
    , zinc                    numeric
    , crp                     numeric
    , agp                     numeric
    , iodine                  numeric
    , time_of_day_sampled     text check (time_of_day_sampled in ('am','pm') )
    , was_fasting             boolean

);
COMMENT ON TABLE  Biomarker_measurement IS 'Levels of various biomarkers as measured by sampling blood, urine, or breastmilk from a household member';
COMMENT ON COLUMN Biomarker_measurement.household_member_id IS 'The id of the household member from which the blood, urine, or breastmilk sample was taken';
COMMENT ON COLUMN Biomarker_measurement.date_sampled        IS 'The date when the sample was taken from the body';
COMMENT ON COLUMN Biomarker_measurement.sample_type         IS 'Whether this is a urine, blood, or breastmilk sample';
COMMENT ON COLUMN Biomarker_measurement.haemoglobin         IS 'The amount of haemoglbin (also known as hemoglobin) in the blood, in grams per litre.';
COMMENT ON COLUMN Biomarker_measurement.ferritin            IS 'The amount of (serum or plasma) Ferritn found in the blood, in micrograms per litre';
COMMENT ON COLUMN Biomarker_measurement.stfr                IS 'The amount of (serum or plasma) Soluble Transferrin Receptors (sTfR) in the blood, in milligrams per litre';
COMMENT ON COLUMN Biomarker_measurement.rbp                 IS 'The amount of (serum or plasma) Retinol Binding Protein (RBP) in the blood, in micromoles per litre';
COMMENT ON COLUMN Biomarker_measurement.retinol             IS 'The amount of (serum or plasma) Retinol in the blood, in micromoles per litre';
COMMENT ON COLUMN Biomarker_measurement.rbc_folate          IS 'The amount of red blood cell Folate in the blood, in nanomoles per litre';
COMMENT ON COLUMN Biomarker_measurement.ps_folate           IS 'The amount of serum or plasma Folate in the blood, in nanomoles per litre';
COMMENT ON COLUMN Biomarker_measurement.vitamin_b12         IS 'The amount of (serum or plasma) Vitamin B12 (also known as cobalamin) in the blood, in picomoles per litre';
COMMENT ON COLUMN Biomarker_measurement.zinc                IS 'The amount of (serum or plasma) zinc, in micrograms per decilitre';
COMMENT ON COLUMN Biomarker_measurement.crp                 IS 'The amount of (serum or plasma) C-reactive protein (CRP) in the blood, in milligrams per litre. A value >=5 defines inflammation';
COMMENT ON COLUMN Biomarker_measurement.agp                 IS 'The amount of (serum or plasma) Alpha 1 acid GlycoProtein (AGP) in the blood, in grams per litre. A value >=1 defines inflammation';
COMMENT ON COLUMN Biomarker_measurement.iodine              IS 'The amount of Urinary Iodine, in micrograms per litre. ';
COMMENT ON COLUMN Biomarker_measurement.time_of_day_sampled IS 'Whether the measurement was taken in the morning or afternoon (pre or post noon local time)';
COMMENT ON COLUMN Biomarker_measurement.was_fasting         IS 'Whether the sample was taken while the patient was fasting';
