

create table household_fct_list
(
household_id 	integer primary key references household (id),
fct_list 		text
)
;

comment on table household_fct_list is 'Table to hold the appropriate prioritised fct list for each household';
comment on column household_fct_list.household_id is 'Identifier for the houshold';
comment on column household_fct_list.fct_list is 'Prioritised list of food comsumption table sources (FCT) as generated by function get_fct_list';



