
-- DROP TABLE IF EXISTS fct_list_food_compostion;

CREATE TABLE fct_list_food_compostion (
    id 								integer primary key GENERATED BY DEFAULT AS identity,
    fct_list 						text,
    food_genus_id 					text,
    micronutrient_id               	text,
    micronutrient_composition      	numeric,
    fooditem_column					text,
    fct_used            			integer,
CONSTRAINT fct_list_food_compostion_uk1 UNIQUE (fct_list, food_genus_id, micronutrient_id) 
);
    
-- comments 
COMMENT ON TABLE fct_list_food_compostion IS 'Table to store unique combination of fct prioritised list, food item and compostion';
COMMENT on column fct_list_food_compostion.fct_list is 'Prioritised list of food comsumption table sources (FCT) as generated by function get_fct_list';
COMMENT on column fct_list_food_compostion.food_genus_id is 'Identifier for the food item from fooditem table';
COMMENT on column fct_list_food_compostion.micronutrient_id is 'Micronutrient identifier';
COMMENT on column fct_list_food_compostion.micronutrient_composition is 'Amount of this micronutrient typically found in this food item';
COMMENT on column fct_list_food_compostion.fooditem_column is 'Name of food item';
COMMENT on column fct_list_food_compostion.fct_used is 'Which FCT is the source of the micronutrient_composition value in this record';  